name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Add your test command here
          echo "Running tests..."

      - name: Compile TypeScript
        run: |
          # Assuming you have a TypeScript project, replace with your actual command
          npm install
          npm run build

      - name: Lint code
        run: |
          # Add your linting command here
          echo "Linting code..."